---
class: Aws::AppConfig::Client
methods:
  create_application:
    parameters:
      name:
        types:
        - String
        required: true
      description:
        types:
        - String
        required: false
      tags:
        types:
        - Hash<String,String>
        required: false
  create_configuration_profile:
    parameters:
      application_id:
        types:
        - String
        required: true
      name:
        types:
        - String
        required: true
      description:
        types:
        - String
        required: false
      location_uri:
        types:
        - String
        required: true
      retrieval_role_arn:
        types:
        - String
        required: true
      validators:
        types:
        - Array<Types::Validator>
        required: false
      tags:
        types:
        - Hash<String,String>
        required: false
  create_deployment_strategy:
    parameters:
      name:
        types:
        - String
        required: true
      description:
        types:
        - String
        required: false
      deployment_duration_in_minutes:
        types:
        - Integer
        required: true
      final_bake_time_in_minutes:
        types:
        - Integer
        required: false
      growth_factor:
        types:
        - Float
        required: true
      growth_type:
        types:
        - String
        required: false
      replicate_to:
        types:
        - String
        required: true
      tags:
        types:
        - Hash<String,String>
        required: false
  create_environment:
    parameters:
      application_id:
        types:
        - String
        required: true
      name:
        types:
        - String
        required: true
      description:
        types:
        - String
        required: false
      monitors:
        types:
        - Array<Types::Monitor>
        required: false
      tags:
        types:
        - Hash<String,String>
        required: false
  delete_application:
    parameters:
      application_id:
        types:
        - String
        required: true
  delete_configuration_profile:
    parameters:
      application_id:
        types:
        - String
        required: true
      configuration_profile_id:
        types:
        - String
        required: true
  delete_deployment_strategy:
    parameters:
      deployment_strategy_id:
        types:
        - String
        required: true
  delete_environment:
    parameters:
      application_id:
        types:
        - String
        required: true
      environment_id:
        types:
        - String
        required: true
  get_application:
    parameters:
      application_id:
        types:
        - String
        required: true
  get_configuration:
    parameters:
      application:
        types:
        - String
        required: true
      environment:
        types:
        - String
        required: true
      configuration:
        types:
        - String
        required: true
      client_id:
        types:
        - String
        required: true
      client_configuration_version:
        types:
        - String
        required: false
  get_configuration_profile:
    parameters:
      application_id:
        types:
        - String
        required: true
      configuration_profile_id:
        types:
        - String
        required: true
  get_deployment:
    parameters:
      application_id:
        types:
        - String
        required: true
      environment_id:
        types:
        - String
        required: true
      deployment_number:
        types:
        - Integer
        required: true
  get_deployment_strategy:
    parameters:
      deployment_strategy_id:
        types:
        - String
        required: true
  get_environment:
    parameters:
      application_id:
        types:
        - String
        required: true
      environment_id:
        types:
        - String
        required: true
  list_applications:
    parameters:
      max_results:
        types:
        - Integer
        required: false
      next_token:
        types:
        - String
        required: false
  list_configuration_profiles:
    parameters:
      application_id:
        types:
        - String
        required: true
      max_results:
        types:
        - Integer
        required: false
      next_token:
        types:
        - String
        required: false
  list_deployment_strategies:
    parameters:
      max_results:
        types:
        - Integer
        required: false
      next_token:
        types:
        - String
        required: false
  list_deployments:
    parameters:
      application_id:
        types:
        - String
        required: true
      environment_id:
        types:
        - String
        required: true
      max_results:
        types:
        - Integer
        required: false
      next_token:
        types:
        - String
        required: false
  list_environments:
    parameters:
      application_id:
        types:
        - String
        required: true
      max_results:
        types:
        - Integer
        required: false
      next_token:
        types:
        - String
        required: false
  list_tags_for_resource:
    parameters:
      resource_arn:
        types:
        - String
        required: true
  start_deployment:
    parameters:
      application_id:
        types:
        - String
        required: true
      environment_id:
        types:
        - String
        required: true
      deployment_strategy_id:
        types:
        - String
        required: true
      configuration_profile_id:
        types:
        - String
        required: true
      configuration_version:
        types:
        - String
        required: true
      description:
        types:
        - String
        required: false
      tags:
        types:
        - Hash<String,String>
        required: false
  stop_deployment:
    parameters:
      application_id:
        types:
        - String
        required: true
      environment_id:
        types:
        - String
        required: true
      deployment_number:
        types:
        - Integer
        required: true
  tag_resource:
    parameters:
      resource_arn:
        types:
        - String
        required: true
      tags:
        types:
        - Hash<String,String>
        required: true
  untag_resource:
    parameters:
      resource_arn:
        types:
        - String
        required: true
      tag_keys:
        types:
        - Array<String>
        required: true
  update_application:
    parameters:
      application_id:
        types:
        - String
        required: true
      name:
        types:
        - String
        required: false
      description:
        types:
        - String
        required: false
  update_configuration_profile:
    parameters:
      application_id:
        types:
        - String
        required: true
      configuration_profile_id:
        types:
        - String
        required: true
      name:
        types:
        - String
        required: false
      description:
        types:
        - String
        required: false
      retrieval_role_arn:
        types:
        - String
        required: false
      validators:
        types:
        - Array<Types::Validator>
        required: false
  update_deployment_strategy:
    parameters:
      deployment_strategy_id:
        types:
        - String
        required: true
      description:
        types:
        - String
        required: false
      deployment_duration_in_minutes:
        types:
        - Integer
        required: false
      final_bake_time_in_minutes:
        types:
        - Integer
        required: false
      growth_factor:
        types:
        - Float
        required: false
      growth_type:
        types:
        - String
        required: false
  update_environment:
    parameters:
      application_id:
        types:
        - String
        required: true
      environment_id:
        types:
        - String
        required: true
      name:
        types:
        - String
        required: false
      description:
        types:
        - String
        required: false
      monitors:
        types:
        - Array<Types::Monitor>
        required: false
  validate_configuration:
    parameters:
      application_id:
        types:
        - String
        required: true
      configuration_profile_id:
        types:
        - String
        required: true
      configuration_version:
        types:
        - String
        required: true
