---
class: Aws::ApplicationDiscoveryService::Client
methods:
  initialize:
    parameters:
      credentials:
        types:
        - Aws::CredentialProvider
        required: true
      region:
        types:
        - String
        required: true
      access_key_id:
        types:
        - String
        required: false
      convert_params:
        types:
        - Boolean
        required: false
      endpoint:
        types:
        - String
        required: false
      log_formatter:
        types:
        - Aws::Log::Formatter
        required: false
      log_level:
        types:
        - Symbol
        required: false
      logger:
        types:
        - Logger
        required: false
      profile:
        types:
        - String
        required: false
      retry_limit:
        types:
        - Integer
        required: false
      secret_access_key:
        types:
        - String
        required: false
      session_token:
        types:
        - String
        required: false
      simple_json:
        types:
        - Boolean
        required: false
      stub_responses:
        types:
        - Boolean
        required: false
      validate_params:
        types:
        - Boolean
        required: false
  associate_configuration_items_to_application:
    parameters:
      application_configuration_id:
        types:
        - String
        required: true
      configuration_ids:
        types:
        - Array<String>
        required: true
  create_application:
    parameters:
      name:
        types:
        - String
        required: true
      description:
        types:
        - String
        required: false
  create_tags:
    parameters:
      configuration_ids:
        types:
        - Array<String>
        required: true
      tags:
        types:
        - Array<Types::Tag>
        required: true
  delete_applications:
    parameters:
      configuration_ids:
        types:
        - Array<String>
        required: true
  delete_tags:
    parameters:
      configuration_ids:
        types:
        - Array<String>
        required: true
      tags:
        types:
        - Array<Types::Tag>
        required: false
  describe_agents:
    parameters:
      agent_ids:
        types:
        - Array<String>
        required: false
      filters:
        types:
        - Array<Types::Filter>
        required: false
      max_results:
        types:
        - Integer
        required: false
      next_token:
        types:
        - String
        required: false
  describe_configurations:
    parameters:
      configuration_ids:
        types:
        - Array<String>
        required: true
  describe_export_configurations:
    parameters:
      export_ids:
        types:
        - Array<String>
        required: false
      max_results:
        types:
        - Integer
        required: false
      next_token:
        types:
        - String
        required: false
  describe_export_tasks:
    parameters:
      export_ids:
        types:
        - Array<String>
        required: false
      filters:
        types:
        - Array<Types::ExportFilter>
        required: false
      max_results:
        types:
        - Integer
        required: false
      next_token:
        types:
        - String
        required: false
  describe_tags:
    parameters:
      filters:
        types:
        - Array<Types::TagFilter>
        required: false
      max_results:
        types:
        - Integer
        required: false
      next_token:
        types:
        - String
        required: false
  disassociate_configuration_items_from_application:
    parameters:
      application_configuration_id:
        types:
        - String
        required: true
      configuration_ids:
        types:
        - Array<String>
        required: true
  list_configurations:
    parameters:
      configuration_type:
        types:
        - String
        required: true
      filters:
        types:
        - Array<Types::Filter>
        required: false
      max_results:
        types:
        - Integer
        required: false
      next_token:
        types:
        - String
        required: false
      order_by:
        types:
        - Array<Types::OrderByElement>
        required: false
  list_server_neighbors:
    parameters:
      configuration_id:
        types:
        - String
        required: true
      port_information_needed:
        types:
        - Boolean
        required: false
      neighbor_configuration_ids:
        types:
        - Array<String>
        required: false
      max_results:
        types:
        - Integer
        required: false
      next_token:
        types:
        - String
        required: false
  start_data_collection_by_agent_ids:
    parameters:
      agent_ids:
        types:
        - Array<String>
        required: true
  start_export_task:
    parameters:
      export_data_format:
        types:
        - Array<String>
        required: false
      filters:
        types:
        - Array<Types::ExportFilter>
        required: false
      start_time:
        types:
        - Time
        - DateTime
        - Date
        - Integer
        - String
        required: false
      end_time:
        types:
        - Time
        - DateTime
        - Date
        - Integer
        - String
        required: false
  stop_data_collection_by_agent_ids:
    parameters:
      agent_ids:
        types:
        - Array<String>
        required: true
  update_application:
    parameters:
      configuration_id:
        types:
        - String
        required: true
      name:
        types:
        - String
        required: false
      description:
        types:
        - String
        required: false
