---
class: Aws::ConfigService::Client
methods:
  initialize:
    parameters:
      credentials:
        types:
        - Aws::CredentialProvider
        required: true
      region:
        types:
        - String
        required: true
      access_key_id:
        types:
        - String
        required: false
      convert_params:
        types:
        - Boolean
        required: false
      endpoint:
        types:
        - String
        required: false
      log_formatter:
        types:
        - Aws::Log::Formatter
        required: false
      log_level:
        types:
        - Symbol
        required: false
      logger:
        types:
        - Logger
        required: false
      profile:
        types:
        - String
        required: false
      retry_limit:
        types:
        - Integer
        required: false
      secret_access_key:
        types:
        - String
        required: false
      session_token:
        types:
        - String
        required: false
      simple_json:
        types:
        - Boolean
        required: false
      stub_responses:
        types:
        - Boolean
        required: false
      validate_params:
        types:
        - Boolean
        required: false
  delete_config_rule:
    parameters:
      config_rule_name:
        types:
        - String
        required: true
  delete_configuration_recorder:
    parameters:
      configuration_recorder_name:
        types:
        - String
        required: true
  delete_delivery_channel:
    parameters:
      delivery_channel_name:
        types:
        - String
        required: true
  delete_evaluation_results:
    parameters:
      config_rule_name:
        types:
        - String
        required: true
  deliver_config_snapshot:
    parameters:
      delivery_channel_name:
        types:
        - String
        required: true
  describe_compliance_by_config_rule:
    parameters:
      config_rule_names:
        types:
        - Array<String>
        required: false
      compliance_types:
        types:
        - Array<String>
        required: false
      next_token:
        types:
        - String
        required: false
  describe_compliance_by_resource:
    parameters:
      resource_type:
        types:
        - String
        required: false
      resource_id:
        types:
        - String
        required: false
      compliance_types:
        types:
        - Array<String>
        required: false
      limit:
        types:
        - Integer
        required: false
      next_token:
        types:
        - String
        required: false
  describe_config_rule_evaluation_status:
    parameters:
      config_rule_names:
        types:
        - Array<String>
        required: false
      next_token:
        types:
        - String
        required: false
      limit:
        types:
        - Integer
        required: false
  describe_config_rules:
    parameters:
      config_rule_names:
        types:
        - Array<String>
        required: false
      next_token:
        types:
        - String
        required: false
  describe_configuration_recorder_status:
    parameters:
      configuration_recorder_names:
        types:
        - Array<String>
        required: false
  describe_configuration_recorders:
    parameters:
      configuration_recorder_names:
        types:
        - Array<String>
        required: false
  describe_delivery_channel_status:
    parameters:
      delivery_channel_names:
        types:
        - Array<String>
        required: false
  describe_delivery_channels:
    parameters:
      delivery_channel_names:
        types:
        - Array<String>
        required: false
  get_compliance_details_by_config_rule:
    parameters:
      config_rule_name:
        types:
        - String
        required: true
      compliance_types:
        types:
        - Array<String>
        required: false
      limit:
        types:
        - Integer
        required: false
      next_token:
        types:
        - String
        required: false
  get_compliance_details_by_resource:
    parameters:
      resource_type:
        types:
        - String
        required: true
      resource_id:
        types:
        - String
        required: true
      compliance_types:
        types:
        - Array<String>
        required: false
      next_token:
        types:
        - String
        required: false
  get_compliance_summary_by_resource_type:
    parameters:
      resource_types:
        types:
        - Array<String>
        required: false
  get_discovered_resource_counts:
    parameters:
      resource_types:
        types:
        - Array<String>
        required: false
      limit:
        types:
        - Integer
        required: false
      next_token:
        types:
        - String
        required: false
  get_resource_config_history:
    parameters:
      resource_type:
        types:
        - String
        required: true
      resource_id:
        types:
        - String
        required: true
      later_time:
        types:
        - Time
        - DateTime
        - Date
        - Integer
        - String
        required: false
      earlier_time:
        types:
        - Time
        - DateTime
        - Date
        - Integer
        - String
        required: false
      chronological_order:
        types:
        - String
        required: false
      limit:
        types:
        - Integer
        required: false
      next_token:
        types:
        - String
        required: false
  list_discovered_resources:
    parameters:
      resource_type:
        types:
        - String
        required: true
      resource_ids:
        types:
        - Array<String>
        required: false
      resource_name:
        types:
        - String
        required: false
      limit:
        types:
        - Integer
        required: false
      include_deleted_resources:
        types:
        - Boolean
        required: false
      next_token:
        types:
        - String
        required: false
  put_config_rule:
    parameters:
      config_rule:
        types:
        - Types::ConfigRule
        required: true
  put_configuration_recorder:
    parameters:
      configuration_recorder:
        types:
        - Types::ConfigurationRecorder
        required: true
  put_delivery_channel:
    parameters:
      delivery_channel:
        types:
        - Types::DeliveryChannel
        required: true
  put_evaluations:
    parameters:
      evaluations:
        types:
        - Array<Types::Evaluation>
        required: false
      result_token:
        types:
        - String
        required: true
      test_mode:
        types:
        - Boolean
        required: false
  start_config_rules_evaluation:
    parameters:
      config_rule_names:
        types:
        - Array<String>
        required: false
  start_configuration_recorder:
    parameters:
      configuration_recorder_name:
        types:
        - String
        required: true
  stop_configuration_recorder:
    parameters:
      configuration_recorder_name:
        types:
        - String
        required: true
