---
class: Aws::ServerlessApplicationRepository::Client
methods:
  initialize:
    parameters:
      credentials:
        types:
        - Aws::CredentialProvider
        required: true
      region:
        types:
        - String
        required: true
      access_key_id:
        types:
        - String
        required: false
      convert_params:
        types:
        - Boolean
        required: false
      endpoint:
        types:
        - String
        required: false
      log_formatter:
        types:
        - Aws::Log::Formatter
        required: false
      log_level:
        types:
        - Symbol
        required: false
      logger:
        types:
        - Logger
        required: false
      profile:
        types:
        - String
        required: false
      retry_limit:
        types:
        - Integer
        required: false
      secret_access_key:
        types:
        - String
        required: false
      session_token:
        types:
        - String
        required: false
      stub_responses:
        types:
        - Boolean
        required: false
      validate_params:
        types:
        - Boolean
        required: false
  create_application:
    parameters:
      author:
        types:
        - String
        required: false
      description:
        types:
        - String
        required: false
      home_page_url:
        types:
        - String
        required: false
      labels:
        types:
        - Array<String>
        required: false
      license_body:
        types:
        - String
        required: false
      license_url:
        types:
        - String
        required: false
      name:
        types:
        - String
        required: false
      readme_body:
        types:
        - String
        required: false
      readme_url:
        types:
        - String
        required: false
      semantic_version:
        types:
        - String
        required: false
      source_code_url:
        types:
        - String
        required: false
      spdx_license_id:
        types:
        - String
        required: false
      template_body:
        types:
        - String
        required: false
      template_url:
        types:
        - String
        required: false
  create_application_version:
    parameters:
      application_id:
        types:
        - String
        required: true
      semantic_version:
        types:
        - String
        required: true
      source_code_url:
        types:
        - String
        required: false
      template_body:
        types:
        - String
        required: false
      template_url:
        types:
        - String
        required: false
  create_cloud_formation_change_set:
    parameters:
      application_id:
        types:
        - String
        required: true
      parameter_overrides:
        types:
        - Array<Types::ParameterValue>
        required: false
      semantic_version:
        types:
        - String
        required: false
      stack_name:
        types:
        - String
        required: false
  delete_application:
    parameters:
      application_id:
        types:
        - String
        required: true
  get_application:
    parameters:
      application_id:
        types:
        - String
        required: true
      semantic_version:
        types:
        - String
        required: false
  get_application_policy:
    parameters:
      application_id:
        types:
        - String
        required: true
  list_application_versions:
    parameters:
      application_id:
        types:
        - String
        required: true
      max_items:
        types:
        - Integer
        required: false
      next_token:
        types:
        - String
        required: false
  list_applications:
    parameters:
      max_items:
        types:
        - Integer
        required: false
      next_token:
        types:
        - String
        required: false
  put_application_policy:
    parameters:
      application_id:
        types:
        - String
        required: true
      statements:
        types:
        - Array<Types::ApplicationPolicyStatement>
        required: false
  update_application:
    parameters:
      application_id:
        types:
        - String
        required: true
      author:
        types:
        - String
        required: false
      description:
        types:
        - String
        required: false
      home_page_url:
        types:
        - String
        required: false
      labels:
        types:
        - Array<String>
        required: false
      readme_body:
        types:
        - String
        required: false
      readme_url:
        types:
        - String
        required: false
